# Create a function in Python named salted_password.
# The function should take in two parameters:	
# Password Chosen By User
# Salt - This is normally generated by this code but for this exercise it will be passed to your function: os.urandom(32).hex()
# Your function should append the Salt to the password and hash with the SHA256 function from the hashlib Python module and return the result.
# Your source code should be named password.py

import os
import hashlib

userPassword = input ("Your Password?: ")
# def salted_password(userPassword):
salt = os.urandom(32).hex()
print ("salt ist gleich = ", salt)
#saltHex = hex(salt)
#print ("saltHex ist gleich = ", saltHex)
saltedPassword = userPassword + salt
print (saltedPassword)
hashedSaltedPassword = hashlib.sha256()
hashedSaltedPassword.update(saltedPassword.encode())

print (hashedSaltedPassword.hexdigest())


#return hashedSaltedPassword

#hSP = (salted_password (userPassword))
#print (hashedSaltedPassword) 

    
